version: "2"
services:
  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    restart: always
    volumes:
      - ./server.json:/etc/v2ray/config.json
      - ./v2ray:/etc/v2ray
    ports:
      - 8888:8888
    command: ["v2ray", "-config=/etc/v2ray/config.json"]
